# 各アプリケーションのサブディレクトリを追加
add_subdirectory(SALI2d)
add_subdirectory(SALI3d)
add_subdirectory(SALI3dV2) 
add_subdirectory(SALI3dV3) 
# add_subdirectory(SSBI2SEBR)  # Removed - directory deleted
add_subdirectory(CalcMethodCompare) 
add_subdirectory(TrajectorySali)
# add_subdirectory(sticky_orbit_search)
add_subdirectory(PoincareMap)
add_subdirectory(TrajectoryCalc)
