# 各アプリケーションのサブディレクトリを追加
add_subdirectory(SALI2d)
add_subdirectory(SALI3d)
add_subdirectory(SALI3dV2) 
add_subdirectory(SALI3dV3) 
# add_subdirectory(SSBI2SEBR)  # Removed - directory deleted
# add_subdirectory(CalcMethodCompare) 
add_subdirectory(TrajectorySali)
add_subdirectory(SaliOrbPlane)
add_subdirectory(PoincareMap)
add_subdirectory(TrajectoryCalc)
add_subdirectory(PeriodicOrbitAnalysis)
add_subdirectory(JacobiIntegralCalc)
add_subdirectory(AsteroidOrbitIntersection)
# add_subdirectory(PeriodicOrbitContinuation)  # Directory does not exist
add_subdirectory(ImpulseOrbitSearch)
add_subdirectory(StableManifoldComputation)
add_subdirectory(CoordTransformVerify)
add_subdirectory(ChaosIndicator)
add_subdirectory(ZvcSurface)
